services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ngx_http_route_module.so:/etc/nginx/modules/ngx_http_route_module.so:ro
    develop:
      watch:
        - action: rebuild
          path: ./default.conf
    depends_on:
      - upstream1
      - upstream2

  upstream1:
    build:
      context: ./upstream1
      dockerfile: Dockerfile
    environment:
      - UPSTREAM=upstream1
    expose:
      - "80"

  upstream2:
    build:
      context: ./upstream1
      dockerfile: Dockerfile
    environment:
      - UPSTREAM=upstream2
    expose:
      - "80"
